name: Build Derper on Push

on:
  push:
    branches:
      - main  # 可按需改成你的主分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (latest stable)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install Derper
        run: go install tailscale.com/cmd/derper@latest

      - name: Prepare Derper binary
        run: |
          mkdir -p ./bin
          cp $HOME/go/bin/derper ./bin/derper

      - name: Upload Derper artifact
        uses: actions/upload-artifact@v4
        with:
          name: derper
          path: ./bin/derper
