name: Build and Release Derper

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (latest stable)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Derper
        run: go install tailscale.com/cmd/derper@latest

      - name: Prepare Derper binary
        run: |
          mkdir -p ./bin
          cp $HOME/go/bin/derper ./bin/derper

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/derper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
