name: Build and Release Derper

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go (latest)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Derper
        run: go get tailscale.com/cmd/derper@latest

      - name: Build Derper
        run: go build -o derper tailscale.com/cmd/derper

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: derper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
